import Head from 'next/head'
import State from '../components/State'


export default function Home() {
  return (
    <>
      <Head>
        <title>React Hooks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <State />
    </>
  )
}
