import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import Button from '../components/Button'
import Message from '../components/Message'
import MessageCTC from '../components/MessageCTC'


export default function Home() {
  const [num, setNum] = useState(0)
  const [num2, setNum2] = useState(0)

  return (
    <>
      <Head>
        <title>React Hooks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href={'/hooks/State'}>useState</Link><br/>
      <Link href={'/hooks/Effect'}>useEffect</Link>

      <Message count={num}/>
      <Button  count={num} upDate={(num) => setNum(num)}/> 
      <hr />

      <MessageCTC count={num2} upDate={(num) => setNum2(num)}/>
     </>
  )
}
